# Generated by Django 2.0.8 on 2018-09-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=15)),
                ('Last_Name', models.CharField(max_length=15)),
                ('Email', models.EmailField(default='xyz@gmail.com', max_length=254)),
                ('Age', models.IntegerField(default=20)),
                ('Mobile', models.BigIntegerField()),
                ('Gender', models.CharField(max_length=5)),
                ('Reamrks', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
