# Generated by Django 2.0.8 on 2018-09-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudApp', '0002_auto_20180917_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studdb',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
    ]
